steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deployment/Dockerfile', '-t', 'us-central1-docker.pkg.dev/apgiframework-web/apgi-images/apgi-api:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/apgiframework-web/apgi-images/apgi-api:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - apgi-api
      - --image=us-central1-docker.pkg.dev/apgiframework-web/apgi-images/apgi-api:$SHORT_SHA
      - --region=us-central1
      - --port=8000
images:
  - 'us-central1-docker.pkg.dev/apgiframework-web/apgi-images/apgi-api:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
